apiVersion: v1
kind: Pod
metadata:
  name: ip-logger
spec:
  serviceAccountName: ecr-access
  containers:
    - name: ip-logger
      image: ACCOUN_ID.dkr.ecr.REGION.amazonaws.com/devops-test-repo:ipLogger
      volumeMounts:
        - name: shared-storage
          mountPath: /data
      command: ["/bin/sh"]
      args: ["-c", "cron -f"]

    - name: s3-uploader
      image: <aws_account_id>.dkr.ecr.REGION.amazonaws.com/devops-test-repo:s3Uploader
      volumeMounts:
        - name: shared-storage
          mountPath: /data
      command: ["/bin/sh"]
      args: ["-c", "crond -f"]

  volumes:
    - name: shared-storage
      emptyDir: {}
    - name: my-secret
