name: 'Deploy branch feature'

on:
  workflow_dispatch: 
  push:
    paths:
      - "Terraform/**"
    branches:
      - feature

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Terraform
    env: 
      TF_VAR_access_key: ${{ secrets.TF_AWS_ACCESS_KEY }}
      TF_VAR_secret_key: ${{ secrets.TF_AWS_SECRET_KEY}}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      env:
        TF_VAR_access_key: ${{ secrets.TF_AWS_ACCESS_KEY }}
        TF_VAR_secret_key: ${{ secrets.TF_AWS_SECRET_KEY }}
      run: terraform plan
