name: 'deploy'

on:
  workflow_dispatch: 
  push:
    branches:
      - feature
  pull_request:
    branches:
      - develop

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env: 
      AWS_ACCESS_KEY_ID: ${{ secrets.TF_AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_AWS_SECRET_KEY}}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.TF_AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_AWS_SECRET_KEY }}
      run: terraform plan -var "access_key=$TF_AWS_ACCESS_KEY" \
           -var  "secret_key=$TF_AWS_SECRET_KEY"

  apply:
    if: github.event.pull_request.merged == true
    needs: [terraform]
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve
