name: 'Deploy branch develop'

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "Terraform/**"
    branches:
      - develop

jobs:
  apply:
    if: github.event.pull_request.merged == true
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve
